[package]
name = "window-melonager"
version = "0.1.0"
authors = ["trickypr <trickypr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.9"
